spring.application.name=back-end

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/book_journal
spring.datasource.username=postgres
spring.datasource.password=091223

# DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# OPCIONAL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true